/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libin_factory_ndk_NDK */

#ifndef _Included_com_libin_factory_ndk_NDK
#define _Included_com_libin_factory_ndk_NDK

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libin_factory_ndk_NDK
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libin_factory_ndk_NDK_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_libin_factory_ndk_NDK
 * Method:    getString_From_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libin_factory_ndk_NDK_getString_1From_1c
  (JNIEnv *, jclass);

/*
 * Class:     com_libin_factory_ndk_NDK
 * Method:    getint
 * Signature: ()Ljava/lang/int;
 */
JNIEXPORT jint JNICALL
Java_com_libin_factory_ndk_NDK_getint(JNIEnv *env, jclass type);

#ifdef __cplusplus
}
#endif
#endif
