package com.libin.factory.green_dao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.libin.factory.green_dao.bean.ProcutedBean;
import com.libin.factory.green_dao.bean.SaleBean;
import com.libin.factory.green_dao.bean.ShopBean;

import com.libin.factory.green_dao.dao.ProcutedBeanDao;
import com.libin.factory.green_dao.dao.SaleBeanDao;
import com.libin.factory.green_dao.dao.ShopBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig procutedBeanDaoConfig;
    private final DaoConfig saleBeanDaoConfig;
    private final DaoConfig shopBeanDaoConfig;

    private final ProcutedBeanDao procutedBeanDao;
    private final SaleBeanDao saleBeanDao;
    private final ShopBeanDao shopBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        procutedBeanDaoConfig = daoConfigMap.get(ProcutedBeanDao.class).clone();
        procutedBeanDaoConfig.initIdentityScope(type);

        saleBeanDaoConfig = daoConfigMap.get(SaleBeanDao.class).clone();
        saleBeanDaoConfig.initIdentityScope(type);

        shopBeanDaoConfig = daoConfigMap.get(ShopBeanDao.class).clone();
        shopBeanDaoConfig.initIdentityScope(type);

        procutedBeanDao = new ProcutedBeanDao(procutedBeanDaoConfig, this);
        saleBeanDao = new SaleBeanDao(saleBeanDaoConfig, this);
        shopBeanDao = new ShopBeanDao(shopBeanDaoConfig, this);

        registerDao(ProcutedBean.class, procutedBeanDao);
        registerDao(SaleBean.class, saleBeanDao);
        registerDao(ShopBean.class, shopBeanDao);
    }
    
    public void clear() {
        procutedBeanDaoConfig.clearIdentityScope();
        saleBeanDaoConfig.clearIdentityScope();
        shopBeanDaoConfig.clearIdentityScope();
    }

    public ProcutedBeanDao getProcutedBeanDao() {
        return procutedBeanDao;
    }

    public SaleBeanDao getSaleBeanDao() {
        return saleBeanDao;
    }

    public ShopBeanDao getShopBeanDao() {
        return shopBeanDao;
    }

}
